USE db_furnitureShop;

INSERT INTO role (id, name, description) VALUES (1, 'admin', 'Administrator'), (2, 'default', 'Default role');

INSERT INTO user (id, birthday, email, lastLogin, firstName, lastName, male, newsletterEnabled, password, username, roleId) VALUES(1, '2013-01-01', 'hero@mailinator.com', '2013-11-11', 'Hero', 'Superman', 1, 1, 'huhuhuhu', 'hero', 1);
INSERT INTO user (id, birthday, email, lastLogin, firstName, lastName, male, newsletterEnabled, password, username, roleId) VALUES(2, '2013-01-01', 'gigu@mailinator.com', '2013-11-11', 'Gigu', 'Wixxer', 1, 1, 'huhuhuhu', 'gigu', 2);

INSERT INTO `category` (`id`, `name_de`, `name_en`, `isOpen`, `orderDate`, `roleId`) VALUES
(1, 'Betten', 'Bed', 0, NULL, NULL),
(2, 'Leuchten', 'Luminaire', 0, NULL, NULL),
(3, 'Sitz&ouml;bel', 'Seating furniture', 0, NULL, NULL),
(4, 'Schlafen', 'Sleep', 0, NULL, NULL),
(5, 'Tische', 'Tables', 0, NULL, NULL);

INSERT INTO `furniture` (`id`, `basicPrice`, `description_de`, `description_en`, `name_de`, `name_en`, `categoryId`) VALUES
(2, 101, 'Eine besondere Designerlampe', 'A Special designerlamp', 'Fontana', 'Fontana', 2),
(3, 133, 'Der About A Chair AAC22 Stuhl von Hay designed von Hee Welling.\r\n\r\nDer Designer von About A Chair hatte eine Vision von der er motiviert wurde: Er wollte einen Stuhl von prÃ¤gnanter Schlichtheit entwickeln. Die Ideen und Impressionen gingen ineinander Ã¼ber und entstanden ist der About A Chair AAC22 - ein Kunstwerk der Einfachheit.\r\n\r\nDer About A Chair Stuhl sollte sowohl als NutzmÃ¶bel und als Designobjekt funktionieren. Der Grundgedanke war, dass der AAC22 Stuhl sowohl am Esstisch, am Konferenztisch, in der Kantine als auch im BÃ¼ro oder in den eigenen vier WÃ¤nden eine gute Figur macht und seinen jeweiligen Zweck erfÃ¼llt. Und das tut er mit Bravour. Er ist ein Allround-Talent und wirklich Ã¼berall einsetzbar.\r\n\r\nDurch seine Armlehnen bietet er einen hervorragenden Sitzkomfort. Die Sitzschale besteht aus durchgefÃ¤rbtem Polypropylen in den unterschiedlichsten Farben, der Rahmen ist aus Buchenholz gefertigt. Das Vierbeingestell ist entwerder in Eiche natur oder in schwarz gebeizter Esche erhÃ¤ltlich.\r\n\r\nHee Welling hat mit dem About A Chair AAC22 Stuhl eine neue Ebene des Designs erreicht und eine bequeme SitzmÃ¶glichkeit im hochwertigsten Stil erschaffen.', 'Hay ''About a Chair "AC22"'' by Hee Willing. The "About a Chair" range embodies an ideal that has motivated its designers. They desired to conceive a chair that would be pointedly simple in its design and construction. This chair was to be equally at home at the dining table and in the conference room, in the canteen and in the office, and - further - it was thus to excel both as a practical item of furniture and as a design object. With "About a Chair", its designer, Hee Welling, has aimed to achieve a higher synthesis of form, function, comfort, detail and aesthetics.', 'About a Chair AAC10', 'About a Chair AAC10', 3),
(4, 350, 'Stetig an den bestehenden Kollektionen arbeiten und den Wert der MÃ¶bel dadurch zu steigern, das ist das strategische Ziel der Fa. Bontempi schon seit Generationen.\r\nDesign verbunden mit FunktionalitÃ¤t ist die Idee der FirmengrÃ¼nder gewesen. ', 'Premium quality chair by Italian Bontempi Casa. Steel chair with removable cover in the finishes.', 'Bontempi Casa - Asia Stuhl', 'Bontempi Casa - Asia Chair', 3),
(5, 101, 'Die Stuhl Kollektion Air Chair wurde 2000 von Jasper Morrison fÃ¼r Magis entworfen.', 'The chair collection Air Chair was designed in the year 2000 by Jasper Morrison for Magis.', 'Magis Air Chair', 'Magis Air Chair', 3),
(6, 1020, 'Struktur aus fliessgepresstem Aluminium und Aluminiumdruckgussteilen poliert oder lackiert in den Farben schwarz, silberglÃ¤nzend oder dunkelgrau metalisiert. Bezug aus Polyester-gewebe mit feuerhemmendem PVC beschichtet in diversen Farben und Leder schwarz.\r\nDesign Alberto Meda\r\n', 'Polished aluminium structure with PVC covered polyester mesh seat and back.', 'Bigframe Stuhl', 'Bigframe Chair', 3),
(7, 128, 'Stefano Giovannoni ist damit bekannt geworden, dass er verspielte, humorvolle Designs mit innovativer FunktionalitÃ¤t kombinierte. Dass Giovannoni dies noch immer versteht, beweist der 2007 entstandene Stuhl First Chair, den Giovannoni fÃ¼r Magis entwarf. Chair First ist stapelbar, fÃ¼r den Innen- und AuÃŸenbereich geeignet und seine Form wirkt flieÃŸend und locker. ', 'The first entirely three-dimensional plastic chair, the Chair First is far from ordinary. Designer Stefano Giovannoni took the air-molding technology developed for the Air-Chair to the next level, creating a sophisticated, streamlined profile on a chair that is a single piece. Sturdy, durable, lightweight, stackable. Ohâ€”and comfortable too.\r\n\r\nThe light weight and stackability make these chairs perfect for dining halls, cafÃ©s, patios, and decks. As happy outdoors as inside, Chair First is available in eight colors, including fashion-forward lime green, olive green, and purple.', 'Chair First', 'Chair First', 3),
(8, 3000, 'Einzelnes Rednerpult mit Neigbarkeit und HÃ¶henverstellung oder Gruppenarbeitsplatz: aus SÃ¤ulen, Traversen und TrÃ¤gerrohren entstehen TischlÃ¶sungen in hochstehender Formensprache.', 'A single lectern with height and angle adjustability or group workstations: table solutions are created from pillars, crossbars and support tubes in a superior language of design.', 'USM Kitos Tisch', 'USM Kitos Table', 5),
(9, 2048, 'Eleganter Esstisch, multifunktionaler Konferenztisch oder ergonomischer Arbeitsplatz â€“ der USM Haller Tisch erfÃ¼llt mit diversen Formen, Materialien und Accessoires jede Funktion.', 'An elegant dining room table, a multi-functional conference table or an ergonomic workspace â€“ the USM Haller Table fulfills every function with various forms, materials and accessories.', 'USM Haller Tisch', 'USM Haller Table', 5),
(10, 450, 'Die Selandia-Serie geht in der Formgebung auf das stolze maritime Handwerk zurÃ¼ck. Auf Details und Design wurde groÃŸe Sorgfalt verwendet - mit dem Schwerpunkt auf Bequemlichkeit, FlexibilitÃ¤t und FunktionalitÃ¤t. Selandia ist elegant und gleichzeitig praktisch, da die MÃ¶bel sich zusammenklappen lassen, wenn sie nicht in Gebrauch sind. ', 'A classic, flexible table whose length can be adapted using extension leafs. ', 'Selandia Tisch', 'Selandia Table', 5),
(11, 768, 'Durch die AusfÃ¼hrung der Struktur in Edelstahl eignet sich die gesamte Kollektion tagliatelle fÃ¼r die Nutzung im Freien, fÃ¼gt sich harmonisch in Garten- und GrÃ¼nbereiche ein. Die praktischen Tische sind durch die gefrÃ¤sten Tischplatten, in der Full Color - oder HPL WOOD Version, gekennzeichnet. Die elastischen BÃ¤nder der SitzflÃ¤che und der RÃ¼ckenlehne werden durch eine neue Farbversion: FE10 grau-Melange erweitert, raffinierte fÃ¼r den Einsatz im Innen- und Aussenbereich.', 'Thanks to the addition of the stainless steel structure, the entire tagliatelle collection is suitable for the outdoor use: by blending into the green environment, it creates an atmosphere of sophisticated relaxation. The practical tables are characterised by new milled table tops, available in Full Color white and HPL WOOD. The elastic bands forming the seat and back will be amplified by a new colour: FE10 grey melange, practical and subtle for the Indoor and Outdoor use.', 'Tagliatelle Tisch', 'Tagliatelle Table', 5),
(12, 1024, 'Muuto Split Tisch designed von Staffan Holm.\n\nDer Split Tisch ist aus massiver Eiche, massiver Esche oder schwarz gebeizt hergestellt.\n\nDer Tisch eignet sich sehr gut als Esstisch.', 'STAFFAN HOLM ON THE DESIGN â€œI wanted the table to have an organic expression and to combine a structural solidity with a seemingly more delicate balancing act. The detail of the legs being split and bent has the expression and quality of a skilled cabinet-maker and is likely to become a hallmark of the Split Table.â€', 'Muuto Split Tisch', 'Muuto Split Table', 5);